//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC
    {
        public System.DateTime date_emission { get; set; }
        public decimal quantite { get; set; }
        public string codeU { get; set; }
        public string codeDEPOT { get; set; }
        public string codeBC { get; set; }
        public System.DateTime date_c { get; set; }
    
        public virtual Depot Depot { get; set; }
    }
}
