//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class BE_bac_bac
    {
        public string libelle { get; set; }
        public decimal quantite { get; set; }
        public string codeU { get; set; }
        public string codeCOMMANDE_MARKET { get; set; }
        public string codeDEPOT { get; set; }
        public string codeBE_BAC_BAC { get; set; }
        public System.DateTime date_c { get; set; }
    
        public virtual Commande_marketer Commande_marketer { get; set; }
    }
}
