//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande_marketer
    {
        public Commande_marketer()
        {
            this.BE_bac_bac = new HashSet<BE_bac_bac>();
            this.FacturationMarketers = new HashSet<FacturationMarketer>();
        }
    
        public decimal quantite { get; set; }
        public string codeU { get; set; }
        public string codeFOURNISSEUR { get; set; }
        public string codeMARKETER { get; set; }
        public string codePRODUIT { get; set; }
        public string codeCOMMANDE_MARKETER { get; set; }
        public System.DateTime date_c { get; set; }
    
        public virtual ICollection<BE_bac_bac> BE_bac_bac { get; set; }
        public virtual Fournisseur Fournisseur { get; set; }
        public virtual Marketer Marketer { get; set; }
        public virtual Produit Produit { get; set; }
        public virtual ICollection<FacturationMarketer> FacturationMarketers { get; set; }
    }
}
