//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compte_marketer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compte_marketer()
        {
            this.Transaction_effectuee = new HashSet<Transaction_effectuee>();
        }
    
        public decimal montant_net { get; set; }
        public string codeU { get; set; }
        public string codeMARKETER { get; set; }
        public string codeCOMPTE_MARKETER { get; set; }
        public System.DateTime date_c { get; set; }
    
        public virtual Marketer Marketer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction_effectuee> Transaction_effectuee { get; set; }
    }
}
