//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dette
    {
        public Dette()
        {
            this.JoinDetteToProduits = new HashSet<JoinDetteToProduit>();
        }
    
        public System.DateTime date_dette { get; set; }
        public decimal montant_paye { get; set; }
        public decimal montant_restant { get; set; }
        public decimal montant_total { get; set; }
        public decimal quantite { get; set; }
        public string codeU { get; set; }
        public string codeCLIENT { get; set; }
        public string codeDETTE { get; set; }
        public System.DateTime date_c { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<JoinDetteToProduit> JoinDetteToProduits { get; set; }
    }
}
