//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historique
    {
        public System.DateTime date_connexion { get; set; }
        public System.DateTime date_deconmexion { get; set; }
        public int nbe_tentative { get; set; }
        public string operation_effectuee { get; set; }
        public string codeCompteU { get; set; }
        public string codeHISTORIQUE { get; set; }
    
        public virtual Compte_utilisateur Compte_utilisateur { get; set; }
    }
}
