//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class JoinDetteToProduit
    {
        public string codeU { get; set; }
        public string codePRODUIT { get; set; }
        public string codeDETTE { get; set; }
        public System.DateTime date_c { get; set; }
    
        public virtual Dette Dette { get; set; }
        public virtual Produit Produit { get; set; }
    }
}
