//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class JoinBE_SoutageToNavire
    {
        public string codeU { get; set; }
        public string codeNAVIRE { get; set; }
        public string codeBE_SOUTAGE { get; set; }
        public System.DateTime date_c { get; set; }
    
        public virtual BE_Soutage BE_Soutage { get; set; }
        public virtual Navire Navire { get; set; }
    }
}
