//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taxe
    {
        public Taxe()
        {
            this.JoinTaxeToFacturations = new HashSet<JoinTaxeToFacturation>();
        }
    
        public string libelle { get; set; }
        public decimal taux { get; set; }
        public string codeU { get; set; }
        public string codeTAXE { get; set; }
        public System.DateTime date_c { get; set; }
    
        public virtual ICollection<JoinTaxeToFacturation> JoinTaxeToFacturations { get; set; }
    }
}
