//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_effectuee
    {
        public System.DateTime date_transaction { get; set; }
        public string libelle { get; set; }
        public decimal montant_transaction { get; set; }
        public string codeU { get; set; }
        public string codeCOMPTE_MARKETER { get; set; }
        public string codeTRANSACTION_EFFECTUEE { get; set; }
        public System.DateTime date_c { get; set; }
    
        public virtual Compte_marketer Compte_marketer { get; set; }
    }
}
