//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vente_carburant
    {
        public int compteur_apres { get; set; }
        public int compteur_avant { get; set; }
        public System.DateTime date_vente { get; set; }
        public decimal quantite { get; set; }
        public string codeU { get; set; }
        public string codePOMPE { get; set; }
        public string codePOMPISTE { get; set; }
        public string codeVENTE_CARBURANT { get; set; }
        public System.DateTime date_c { get; set; }
    
        public virtual Pompiste Pompiste { get; set; }
    }
}
