//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Pompe
    {
        public string libelle { get; set; }
        public int pompeID { get; set; }
        public int tankerID { get; set; }
        public System.Guid code { get; set; }
    }
}
