//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Compte_marketer
    {
        public decimal montant_net { get; set; }
        public int compte_marketerID { get; set; }
        public int marketerID { get; set; }
        public System.Guid code { get; set; }
    }
}
