//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Stock
    {
        public decimal quantite { get; set; }
        public int stockID { get; set; }
        public int depotID { get; set; }
        public int marketerID { get; set; }
        public int produitID { get; set; }
        public System.Guid code { get; set; }
    }
}
