//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Vente_carburant
    {
        public int compteur_apres { get; set; }
        public int compteur_avant { get; set; }
        public System.DateTime date_vente { get; set; }
        public decimal quantite { get; set; }
        public int vente_carburantID { get; set; }
        public int pompeID { get; set; }
        public int pompisteID { get; set; }
        public System.Guid code { get; set; }
    }
}
