//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Transaction_effectuee
    {
        public System.DateTime date_transaction { get; set; }
        public string libelle { get; set; }
        public decimal montant_transaction { get; set; }
        public int transaction_effectueeID { get; set; }
        public int compte_marketerID { get; set; }
        public System.Guid code { get; set; }
    }
}
