//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Navire
    {
        public decimal capacite { get; set; }
        public string nom { get; set; }
        public int navireID { get; set; }
        public System.Guid code { get; set; }
    }
}
