//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Facturation
    {
        public System.DateTime date_c { get; set; }
        public string libelle { get; set; }
        public decimal montant_paye { get; set; }
        public decimal montant_restant { get; set; }
        public decimal montant_total { get; set; }
        public int facturationID { get; set; }
        public int commande_clientID { get; set; }
        public System.Guid code { get; set; }
    }
}
