//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Compte_utilisateur
    {
        public string indice { get; set; }
        public string login { get; set; }
        public string mdp { get; set; }
        public string niveau { get; set; }
        public string statut { get; set; }
        public int compte_utilisateurID { get; set; }
        public int utilisateurID { get; set; }
        public System.Guid code { get; set; }
    }
}
