//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Reception
    {
        public System.DateTime date_reception { get; set; }
        public decimal quantite { get; set; }
        public int receptionID { get; set; }
        public int commande_clientID { get; set; }
        public System.Guid code { get; set; }
    }
}
